services:
  - type: web
    name: estudo-rg-concursos
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_concurso:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
